### PR TITLE
[Doc] Fix typo s/dicionary/dictionary/

### PR DESCRIPTION
**Pull request by kachick**

### CODE REVIEW

**Review by pocke — APPROVED** [review]
Thanks!

**Comment by kachick** [comment]
Thank you!

**Comment by pocke** [comment]
Could you remove `ci skip` from the commit message and force push it?
It prevents CI jobs but this repository requires the CI result.

**Comment by kachick** [comment]
>Could you remove ci skip from the commit message and force push it?
It prevents CI jobs but this repository requires the CI result to merge a PR.

I didn't know that 😮 🙇 
And accidentally closed 😓 

So created same PR again https://github.com/ruby/rbs/pull/640 (without `[ci skip]`)

**Pull request closed without merging**
