### PR TITLE
[resolv] Add RBS file for Resolv

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
Added RBS signatures for the `resolv` package, + some tests.

### CODE REVIEW

**Review by soutaro — CHANGES_REQUESTED** [review]
Please fix the name resolution errors like `dns_name`, `Sender`, etc... Write the type names in qualified style or declare classes/modules in nested style.

I also found socket classes are undefined. I think writing socket RBS is too much for this, so just adding empty classes in a file like `resolv/0/sockets.rbs` is good.

**Comment by HoneyryderChuck** [comment]
> I also found socket classes are undefined.

@soutaro I noticed it while reviewing the errors, and went ahead with it [here](https://github.com/ruby/rbs/pull/699). Let's  deal with it first, then I'll revisit this.

**Comment by HoneyryderChuck** [comment]
@soutaro it's ready for review.

> Write the type names in qualified style or declare classes/modules in nested style.

I didn't understand this comment. Can you elaborate?

**Comment by soutaro** [comment]
@HoneyryderChuck Could you remove the trailing whit spaces?

**Comment by HoneyryderChuck** [comment]
@soutaro done.

**Review by soutaro — APPROVED** [review]
👏

**Pull request merged**
