### PR TITLE
Fix LockfileGenerator crashes if failed to get deps for locked source

### LINKED ISSUE #1412: unhandled exception was raised when dependencies are mismatched between Gemfile.lock and rbs_collection.lock.yaml
I got the following error on running `rbs collection install`.

```
$ bundle exec rbs collection install
bundler: failed to load command: rbs (/Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/rbs)
/Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/sources/rubygems.rb:31:in `manifest_of': unhandled exception
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/sources/base.rb:8:in `dependencies_of'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:137:in `assign_gem'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:146:in `block in assign_gem'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:144:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:144:in `assign_gem'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:82:in `block in generate'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:76:in `each'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:76:in `generate'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config/lockfile_generator.rb:27:in `generate'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/collection/config.rb:36:in `generate_lockfile'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/cli.rb:1103:in `run_collection'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/lib/rbs/cli.rb:137:in `run'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rbs-3.1.3/exe/rbs:7:in `<top (required)>'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/rbs:25:in `load'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/rbs:25:in `<top (required)>'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Users/tkomiya/.dotfiles/_rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
        from /Users/tkomiya/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
        from /Users/tkomiya/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```

This error happened when I update Gemfile dependencies (Gemfile.lock). It seems the error comes from the mismatch between Gemfile.lock and rbs_collection.lock.yaml.

I think it's better to catch the exception from `manifest_of()` and print a better error message to users.

### PR DESCRIPTION
**Pull request by tk0miya**
Close #1412

### CODE REVIEW

**Comment by soutaro** [comment]
1. I'm good for this change, but it's not clear to me what is happening. Looks like a gem included in the `rbs_collection.lock.yaml` is not installed?
2. Can you add some test? (Or explain why adding test doesn't make much sense.)

**Comment by tk0miya** [comment]
>I'm good for this change, but it's not clear to me what is happening. Looks like a gem included in the rbs_collection.lock.yaml is not installed?

Yes. This happens if Gemfile.lock and rbs_collection.lock.yaml are mismatched. I got this error after `bundle update`. In particular, dependabot goes to update only Gemfile.lock. So it causes this error in the CI process.

>Can you add some test? (Or explain why adding test doesn't make much sense.)

Okay, I'll try it later.

**Comment by tk0miya** [comment]
Added.

**Review by soutaro — APPROVED** [review]
Thanks!

**Pull request merged**
