### PR TITLE
Use Random::Base for super_class of Random

### PR DESCRIPTION
**Pull request by ksss**
Starting with ruby v3.0, Random::Base was created to facilitate algorithm changes,
and the inheritance relationship was changed.
ref: https://github.com/ruby/ruby/pull/3024

Also, since there was no test, I created a new one.

### CODE REVIEW

**Review by soutaro — APPROVED** [review]
Thank you so much! 🙏

**Comment by soutaro** [comment]
Oh no... What is happening??? How can we have that circular definition in Ruby...

**Comment by soutaro** [comment]
Hmm, the Ruby source code is doing equivalent to the following:

```rb
base = Class.new
Random = Class.new(base)
Random::Base = base
```

**Comment by ksss** [comment]
Yes.

`Random::Base` implemented from https://github.com/ruby/ruby/pull/3024 .
Probably, `Random::Base` is a public API.

**Pull request merged**
