### PR TITLE
Dedup method comments

### LINKED ISSUE #1054: Duplicate comments?
Following the example:

```
> instance.methods[:gsub].comments.size
=> 4
```

Did I do something wrong? The 4 comments all seem identical?

### PR DESCRIPTION
**Pull request by soutaro**
Fixes #1054

### CODE REVIEW

**Comment by ioquatix** [comment]
Do you know why duplicates existed in the first place?

**Comment by soutaro** [comment]
I don't think there was a good reason to have it duplicated. It should be just because of a confusion caused by the complicated structure and bad names... 😓

A def declaration with several overloads has duplicated documentations given to the def declaration.

```rbs
# Doc is for def syntax
def foo: () -> String                  (Overload 1)
       | (Integer) -> Integer          (Overload 2)

# Another doc for another def syntax
def foo: (Integer, Integer) -> void    (Overload 3)
       | ...
```

And the `defs` attribute contains the overloads, 1, 2, and 3, not def syntaxes.

This caused the duplication.

**Comment by ioquatix** [comment]
Would it make sense to have a single source of truth for unique documentation?

In your example case, it seems reasonable that there are 2 distinct "documentation" instances.

**Comment by soutaro** [comment]
Not very sure what do you mean with _a single source of truth_. The `RBS::AST::***#comment` would be the source of truth, and this method is a utility to help collect every comments attached to a method.

In the example above, there will be two comments, for `#foo` method.

* `RBS::AST::Members::MethodDefinition` object for the first def has the first doc
  * The second object has the second doc
  * This is the source of truth
* The comments will be distributed to method overloads, so that we can provide _hover_ feature to show the documents from the source code
  * Overload 1 and 2 have the first doc
  * Overload 3 has the second doc
* The `#comments` method collects the docs through overloads
  * This is the reason of duplication: There are three overloads and we got three comments
  * Deduping the comments will result in two comment object: the first doc and second doc

**Comment by ioquatix** [comment]
I'll try it out and see how it works in practice. Thanks for your help.

**Pull request merged**
