### PR TITLE
URI sig improvements

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
Improving method defs which can receive a generic uri as arg.

Added sigs for new `URI::HTTP` methods added in v0.11.

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
How can I fix the CI issue? it seems that I'd have to copy all prev version sigs, how can I just let them merge, or is the right fix to copy files?

**Comment by HoneyryderChuck** [comment]
ping @soutaro

**Comment by soutaro** [comment]
Hi @HoneyryderChuck, 

Could you move to the updated RBS files to `uri/0`? We don't support providing RBS files for multiple versions, since URI is a default gem, gems which is always available even under bundler.

**Review by soutaro — CHANGES_REQUESTED** [review]
🙏

**Comment by HoneyryderChuck** [comment]
@soutaro done

**Review by soutaro — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
