### PR TITLE
Fix mswin build, use append_cflags, add Windows 'compile only' CI

### PR DESCRIPTION
**Pull request by MSP-Greg**
With ruby-loco's mswin `make install`, the following error is thrown:
```
cl : Command line error D8021 : invalid numeric argument '/Wold-style-definition'
```

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Similar to PR #963...

**Comment by MSP-Greg** [comment]
Sorry.  Not enough coffee yet.

**Comment by MSP-Greg** [comment]
I another commit adding Windows CI using ucrt and mswin, only checking for successful compile.  In my fork, the jobs failed for the mswin builds when the first commit wasn't included.

**Review by soutaro — APPROVED** [review]
@MSP-Greg Thank you! 🎉

**Pull request merged**
