### PR TITLE
Generate nested declarations

### PR DESCRIPTION
**Pull request by raosush**
# Description
- Generate nested declarations while using `rbs prototype runtime`

# Proposal
* **Detailed Proposal can be found here**: https://hackmd.io/@sushanth/SygRrau2_

# Example
image

Fixes: #562

Signed-off-by: Sushanth Sathesh Rao <rao.sush004@gmail.com>

### CODE REVIEW

**Comment by raosush** [comment]
- [ ] Update `RuntimePrototypeTest.rb`

**Comment by soutaro** [comment]
Great improvement! 👏 

The code looks good generally. Update the test please, then I can finalize the PR/review.

**Comment by raosush** [comment]
> Update the test please, then I can finalize the PR/review.

@soutaro Sir, the test has been updated and all checks are passing

**Review by soutaro — APPROVED** [review]
Great work! 👏

**Pull request merged**
