### PR TITLE
Fixup dependabot

### PR DESCRIPTION
**Pull request by soutaro**

### CODE REVIEW

**Comment by ParadoxV5** [comment]
I’m concerned that this will automatically accept breaking changes even if they fail CI.

Also, if the intent is to automatically bump teeny versions and transitive deps for `Gemfile.lock`, I recommend simply removing it from the repo, so a fresh checkout/clean (including CIs) will force `bundle` to look up the latest versions as part of `bundle install`.

**Comment by soutaro** [comment]
No. This won't merge PRs when CI fails.

Dependabot won't change gemspec files. So the potential minor unstableness increase for the dev team is acceptable I think. 

I don't think removing Gemfile.lock from the repo is a good idea. My experience was it caused more problems -- CI starts failing randomly if a release of a gem causes an issue.

**Comment by ParadoxV5** [comment]
> No. This won't merge PRs when CI fails.

I just noted that `rbs` uses Merge Queue, which can be configured to reject failing PRs. However, it doesn’t look like `steep` and `rbs-inline` are also using the queue.

> Dependabot won't change gemspec files.

Dependabot *can* update `.gemspec`s. E.g.,
* ParadoxV5/template-ruby-gem#3

> I don't think removing Gemfile.lock from the repo is a good idea. My experience was it caused more problems -- CI starts failing randomly if a release of a gem causes an issue.

We can always pin specific versions or adjust the bounds (lower or upper) to exclude problematic versions.
In fact, *if* we need to do that, we shouldn’t specify the constraints just in `Gemfile.lock`, but rather `.gemspec` so they’re included in releases.

**Comment by soutaro** [comment]
Oops. My bad. We need a config not to update the .gemspec. 

It specifies --auto option with gh merge command. It enables auto-merge, and CI fails reject merging the PRs.

**Comment by ParadoxV5** [comment]
> Oops. My bad. We need a config not to update the .gemspec.

Why 😕?

> It specifies --auto option with gh merge command. It enables auto-merge, and CI fails reject merging the PRs.

👍

**Comment by soutaro** [comment]
> we shouldn’t specify the constraints just in Gemfile.lock

It may be true in theory, but practically I don't want to compose PRs to pin gems in Gemfile. If this is only for the developments, because this is a gem, I believe having the lockfile is a reasonable balance.

**Comment by soutaro** [comment]
> Why 😕?

Hmm. What I want exactly is:

1. Merge automatically updating gems in the lockfile, which is used for developments.
2. Merge after reviewing if it changes .gemspec dependency, because it is an update for releases.

Maybe we can do it...

**Comment by soutaro** [comment]
The gemspec doesn't have any dependency with version constraints!

**Comment by ParadoxV5** [comment]
> 2. Merge after reviewing if it changes .gemspec dependency, because it is an update for releases.

With Dependabot PRs automatically merging, we can easily overlook them even if they affect the `.gemspec`, especially for `steep`’s large assortment of dependencies.
The thing is, isn’t this _a_ reason why Dependabot opens PRs – to give maintainers opportunity to review?

> The gemspec doesn't have any dependency with version constraints!

For `rbs`, at least. Could this also be intended? 🤔

**Comment by ParadoxV5** [comment]
@pocke any comments?

**Pull request merged**
