### PR TITLE
WIP: add minitest mock speck unit rbs files and tests

### PR DESCRIPTION
**Pull request by wildeng**
Added Minitest mock, speck and unit signature files with tests for mock only

### CODE REVIEW

**Comment by hsbt** [comment]
@wildeng Thanks for your work. But `minitest` is not standard library of the Ruby language. https://github.com/ruby/gem_rbs_collection is the right place of `minitest`.

**Comment by wildeng** [comment]
Thanks a lot @hsbt I will decline the PR. Should I also update the Google sheet given that minitest is listed there?

**Comment by soutaro** [comment]
Thanks @wildeng @hsbt,

I will update the spreadsheet. I'm not sure if there are other gems on the sheet.

**Comment by wildeng** [comment]
Closing as per previouse comments

**Pull request closed without merging**
