### PR TITLE
Creates the signature for the DBM  

### PR DESCRIPTION
**Pull request by PanosCodes**
Creates the signature for the DBM  & tests

### CODE REVIEW

**Comment by PanosCodes** [comment]
Any thought why the `require "dbm"` does not work on tests https://github.com/ruby/rbs/pull/441/checks?check_run_id=1275835013 ?
```
test/stdlib/DBM_test.rb:2:in `require': cannot load such file -- dbm (LoadError)
```

**Comment by PanosCodes** [comment]
The dbm gem is missing from the image  🤔

**Comment by soutaro** [comment]
I got it. It's a problem...

**Comment by soutaro** [comment]
Opened a pull request to set up dbm library: https://github.com/ruby/rbs/pull/460

Could you rebase this PR on the top of #460 so that we can confirm the fix works?

**Comment by PanosCodes** [comment]
> Opened a pull request to set up dbm library: #460
> 
> Could you rebase this PR on the top of #460 so that we can confirm the fix works?

Done. The tests seem fine ✅, thank you for your work.

**Review by soutaro — APPROVED** [review]
Thanks!

**Pull request merged**
